import localFont from "next/font/local";
import "./globals.css";

const neuemontreal = localFont({
  src: [
    {
      path: "../../public/fonts/PPNeueMontreal-Medium.woff2",
    },
  ],
  display: "block",
  variable: "--font-neuemontreal",
});

const neuemontrealcondensed = localFont({
  src: [
    {
      path: "../../public/fonts/OTNeueMontreal-MediumSqueezed.woff",
    },
  ],
  display: "block",
  variable: "--font-neuemontrealcondensed",
});

const denton = localFont({
  src: [
    {
      path: "../../public/fonts/DentonVariableTest-VF.otf",
    },
  ],
  display: "block",
  variable: "--font-denton",
});




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`fixed h-full w-full top-0 ${neuemontrealcondensed.variable} ${denton.variable} ${neuemontreal.variable}`}>
      <body >
      <svg className="pointer-events-none cursor-none absolute">
            <filter id="grainy">
              <feTurbulence type="turbulence" baseFrequency="0.40" />
              <feColorMatrix type="saturate" values="0" />
            </filter>
          </svg>
        {children}</body>
    </html>
  );
}
